version: "3.7"

services: 
    database_api:
        image: postgres
        container_name: database_api
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=leo
            - POSTGRES_PASSWORD=dev
            - POSTGRES_DB=dbapi
        volumes:
            - pgdata:/data/postgres
        
    app:
        build: .
        container_name: api
        ports: 
            - 3333:3333
            - 9229:9229
        volumes:
            - .:/usr/app
        links:
            - database_api
        depends_on:
            - database_api

volumes:
    pgdata:
        driver: local